# Generated by Django 5.1.4 on 2026-06-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, default='', max_length=16)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('day', models.CharField(blank=True, default='', max_length=8)),
                ('month', models.CharField(blank=True, default='', max_length=8)),
                ('weekday', models.CharField(blank=True, default='', max_length=24)),
                ('time', models.CharField(blank=True, default='', max_length=16)),
                ('artist', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, default='')),
                ('tag', models.CharField(blank=True, default='', max_length=40)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
                ('alt', models.CharField(blank=True, default='', max_length=160)),
                ('span', models.CharField(blank=True, default='', max_length=20)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'foto da galeria',
                'verbose_name_plural': 'fotos da galeria',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('tagline', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp_message', models.TextField(blank=True, default='')),
                ('instagram', models.CharField(blank=True, default='', max_length=200)),
                ('instagram_handle', models.CharField(blank=True, default='', max_length=80)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('maps_query', models.CharField(blank=True, default='', max_length=200)),
                ('maps_embed', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=200)),
                ('hours', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'configuração do site',
                'verbose_name_plural': 'configuração do site',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('serves', models.CharField(blank=True, default='', max_length=80)),
                ('image', models.TextField(blank=True, default='')),
                ('badge', models.CharField(blank=True, default='', max_length=40)),
                ('best_seller', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('variations', models.JSONField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cardapio.category')),
            ],
            options={
                'verbose_name': 'item do cardápio',
                'verbose_name_plural': 'itens do cardápio',
                'ordering': ['sort'],
            },
        ),
    ]
