# Generated by Django 5.1.4 on 2026-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
