# Generated by Django 5.1.4 on 2026-08-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_siteconfig_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
                ('caption', models.CharField(blank=True, default='', max_length=120)),
                ('alt', models.CharField(blank=True, default='', max_length=160)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'foto de bebida/drink',
                'verbose_name_plural': 'fotos de bebidas/drinks',
                'ordering': ['sort'],
            },
        ),
    ]
