# Generated by Django 5.1.4 on 2026-08-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_drinkphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.TextField(blank=True, default=''),
        ),
    ]
